name: Ant Build Process
on:
  workflow_call:  # Esto permite que otro workflow lo llame

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      
      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Instalar Apache Ant
        run: sudo apt-get install ant

      - name: Ejecutar Ant
        run: ant -f build.xml
