name: Ant Build 
on:
  workflow_dispatch:  
  pull_request:
    branches:
      - develop  
      - qa_split
  push:
    paths-ignore:     
      - '.github/**'
      - '*.md'
    branches: 
      - develop
      - qa_split
      - qa
      - main
      - drp
jobs:
  cicd:
    uses: ./.github/workflows/ant.yml    
    secrets: inherit
